_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.19
        t:
            "1":
                - 1
                - 5
                - 11
                - 33
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 100
            "2":
                - 1
                - 5
                - 11
                - 33
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 100
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.19
            "5": 0.19.9
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
architecture:
    value: stacked
batchsize:
    value: 512
dataset:
    value: mscoco
epochs:
    value: 100
learning_rate:
    value: 0.001
